name = "clfc-spinning-wheel"
main = "_worker.js"
compatibility_date = "2026-08-19"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "clfchub"
database_id = "199c7c5a-b202-4439-9401-4c2f27e33ea5"
